_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin_homepage:
    pattern: /admin
    defaults: { _controller: SonataUserBundle:AdminSecurity:login}

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin