fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin_homepage:
    pattern: /admin
    defaults: { _controller: SonataUserBundle:AdminSecurity:login}

main_routing:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin